### PR TITLE
fix comments. fix getPlaylists

### PR DESCRIPTION
**Pull request by WiRight**
- Fix comments of getPlaylists function
- Fix getPlaylists function (join is not a method of String)
- Check markdown lint (README.me)
- Add .editorconfig
- Format code

### CODE REVIEW

**Comment by itsmepetrov** [comment]
Hi @WiRight, thanks for your great job!
I'll try to check your PR today later.
Unfortunately, this library doesn't have tests and it's hard to maintain it.

**Comment by WiRight** [comment]
Hey!
Okay, no problem!)
See you soon

**Review by itsmepetrov — APPROVED** [review]
LGTM

**Comment by itsmepetrov** [comment]
@WiRight would you like to update other js files in next PR for consistency?

**Comment by WiRight** [comment]
@itsmepetrov  Yeah, when I find mistakes like this

**Pull request merged**
